### ISSUE TITLE
Update with LIMIT error

### ISSUE THREAD

**Issue by jaumard** [trailsjs/trailpack-waterline#13]
When trying to make an update on multiple records I have this error : 

```
Details:  Error: UPDATE "user" SET  "name" = 'updatetest2', "updatedAt" = 'Fri, 08 Jan 2016 07:49:57 GMT'  WHERE LOWER("user"."name") = 'updatetest1'  LIMIT 100 - SQLITE_ERROR: near "LIMIT": syntax error
```

Delete the limite fix this.

**Comment by tjwebb** [comment]
What is the waterline query you're using? Or is this being sent through FootprintService?

**Comment by jaumard** [comment]
Yeah directly with `FootprintService.update` I just comment the https://github.com/trailsjs/trailpack-waterline/blob/master/api/services/FootprintService.js#L85 and all is working after

**Comment by jaumard** [comment]
My call is here https://github.com/jaumard/trailpack-express4/blob/master/api/controllers/FootprintController.js#L49

**Comment by jaumard** [comment]
Ok just found why it append to me and not for trailpack-hapi, it's because on config I have : 

```
options: {
        defaultLimit: 100,
        watch: false,
        populate: true
      },
```

When you have only : 

```
options: {
        populate: true
      },
```

If you add this limit the trailpack-hapi crash too

**Comment by tjwebb** [comment]
Looking into this today. I'll try to add tests in trailpack-waterline to catch this.
