### ISSUE TITLE
Many-to-many relation : Internal Server Error

### ISSUE THREAD

**Issue by PPCM** [trailsjs/trailpack-waterline#25]
I have 2 models, and I would to make a relation many-to-many between them:

Group model:

```
{
      name: {
        type: 'string'
      },

      users: {
        collection: 'user',
        via: 'groups'
      }
    }

```

User model:

```
{
      username: {
        type: 'string'
      },

      groups: {
        collection: 'group',
        via: 'users',
        dominant: true
      }
}
```

The goal is to populate stores with REST resquests.
Group and User stores were populate with datas, but when I try to make relations between the 2 models with a POST or PUT request like `http://myserver:3000/api/v1/user/1/groups`, but each time the following error occurs:

```
{
    "statusCode": 500,
    "error": "Internal Server Error",
    "message": "An internal server error occurred"
}
```

I made some tests with a relation one-to-many and it works perfectly.

Perhaps it is a wrong usage with many-to-many relation...

**Comment by tjwebb** [comment]
Which adapter are you using? Do you get a stacktrace in the console?

**Comment by PPCM** [comment]
On the console, the following debug message is thrown:
`debug: [FootprintController] (updateAssociation) user 1 -> groups undefined , criteria =`

But groups is well defined in User model

I use waterline-sqlite3 adapter, I didn't try with something else...

**Comment by tjwebb** [comment]
There's an open issue for many-to-many relations in the sqlite adapter that you might be running into: https://github.com/waterlinejs/sqlite3-adapter/issues/1.

Also, the tests I've written for this trailpack thus far haven't tested the many-to-many feature of the Waterline adapters. I'll try to look into it this week, but in general maintaining individual waterline adapters isn't something we're going to be focusing on long-term. Most future work will be in the knex and bookshelf trailpacks.

**Comment by PPCM** [comment]
OK, thanks for the response and for your help
