### ISSUE TITLE
How to make waterline-rethinkdb as an official adapter.

### ISSUE THREAD

**Issue by gutenye** [trailsjs/trailpack-waterline#80]
Hi, all

I'm the author of [waterline-rethinkdb](https://github.com/gutenye/waterline-rethinkdb), I've been using it for months and want to make it as an official adapter, what steps are needed?

I first created [sails-rethinkdb](https://github.com/gutenye/sails-rethinkdb) for sails, as the reasons we know, I switched to trails and want to make a contribute to trails community.

**Comment by scott-wyatt** [comment]
Awesome!!! For the waterline trailpack, waterline adapters get loaded [here](https://github.com/trailsjs/trailpack-waterline/blob/master/lib/transformer.js#L39) so I'd imagine that you would establish a rethink adapter there. I've also been working on a  [js-data](https://github.com/scott-wyatt/trailpack-js-data) ORM that could support rethink, and works with waterline style schema. Hope this helps!

**Comment by jaumard** [comment]
Hi @gutenye ! Normally all waterline adapters has to work with `trailpack-waterline` so I think you can use your `waterline-rethinkdb` directly by putting it under the `config/database.js` file. 
You have an example here where I use the `sails-mongo` adapter with Trails https://github.com/jaumard/trails-example-express/blob/master/config/database.js#L32

**Comment by gutenye** [comment]
@scott-wyatt @jaumard 

Thanks for your helping, I've made it working with trails. :tada:  I want to put this library into https://github.com/waterlinejs as an official adapter. 1) for new users, they don't have to search a lot to find it. 2) for the community,  no need to speed  time to create a new one.

**Comment by jaumard** [comment]
Don't think you can put it as an official adapter because that will means that the waterline team will be officially maintainers of this repo... But you can open an issue on waterline repo to ask the team about this, maybe they'll be agree.

I think the best things to do is a PR to waterline repo and add your adapter into this list but keep it on your github https://github.com/waterlinejs/waterline#community-adapters you can see there a lot of adapters and they're not on the official github.

Copy @tjwebb

**Comment by gutenye** [comment]
After put it as an official adapter, I can still be a maintainer of it. All waterline adapter are essential part of waterline ecosystem, put them in one place is good for maintenance and development, e.g. coding style, code quality.  

I've seen waterline team has been rewriting some adapters in es6, e.g. postgresql-adapter, sqlite3-adapter. I can adapt my repo to fit the missing part.

**Comment by fernandoans** [comment]
gutenye, exists one error in your adapter with create 2 tables in RethinkDB, example: User / user. For resolve this, in class connection.js I blocked:

this.db.tableCreate(name)...

**Comment by gutenye** [comment]
@fernandoans PR is welcome.

It has been not be active for more than a year, close for now.

**Comment by fernandoans** [comment]
In your sails-rethinkdb in file "query.js" a line 63 causes error, the variable/object 'pd' is not defined. 

And if you change line 126: case "contains": return row(field).match(value)
solve problem with contains

**Comment by fernandoans** [comment]
Gift for you :)

"query.js" in line 126:

        case "contains": return row(field).match("(?i)^" + value + "$")
        case "startsWith": return row(field).match("(?i)^" + value)
        case "endsWith": return row(field).match("(?i)" + value + "$")
        case "like": return row(field).match("(?i)" + value.replace('%','.'))

Explanation: (?i) case-insensitive, match uses . in replace % and $ final word
